
CREATE TABLE VISHWA_CONST(CITY_NAME varchar(20) PRIMARY KEY,PRICE_WITH_MATERIAL float(5),PRICE_WITHOUT_MATERIAL float(5));

INSERT INTO VISHWA_CONST VALUES("HYDERABAD",2000,900);
INSERT INTO VISHWA_CONST VALUES("TRIVENDRUM",1600,800);
INSERT INTO VISHWA_CONST VALUES("CHENNAI",1800,1000);
INSERT INTO VISHWA_CONST VALUES("MUMBAI",2500,1200);
INSERT INTO VISHWA_CONST VALUES("KOCHIN",1800,1200);

SELECT (PRICE_WITH_MATERIAL*2) AS TOTAL_AMOUNT_WITH_MATERIAL,(PRICE_WITHOUT_MATERial*2) AS TOTAL_AMOUNT_WITHOUT_MATERIAL FROM VISHWA_CONST WHERE CITY_NAME="HYDERABAD";

SET FOREIGN_KEY_CHECKS=0;
CREATE TABLE CUSTOMER1(CUST_NAME varchar(10),CUST_PHONE_NO varchar(10),CITY_NAME VARCHAR(20),foreign key(CITY_NAME) REFERENCES VISHWA_CONST(CITY_NAME),CUST_SQFT integer(3));

INSERT INTO customer1 VALUES("SOWJANYA",8185818565,"HYDERABAD",2);
INSERT INTO customer1 VALUES("MEGHANA",8185818900,"KODAD",90);
INSERT INTO customer1 VALUES("SOWJANYA",8185818565,"KOCHIN",90);employee
INSERT INTO customer1 VALUES("YASHWANTH",9068818565,"MUMBAI",100);



SELECT C.CUST_NAME,CUST_PHONE_NO,C.CITY_NAME,(V.PRICE_WITH_MATERIAL*C.CUST_SQFT) AS TOTAL_AMT_WITH_MATERIAL,(V.PRICE_WITHOUT_MATERIAL*C.CUST_SQFT) AS TOTAL_AMT_WITHOUT_MATERIAL from vishwa_const V,customer1 C WHERE V.CITY_NAME=C.CITY_NAME;